// Code generated by pigeon; DO NOT EDIT.

//
// Inspired by pegjs arithmetic example:
// https://github.com/pegjs/pegjs/blob/master/examples/arithmetics.pegjs
//
// Inspired from pegjs excel formula parser:
// https://gist.github.com/gamerxl/cf5184a437b10d0f86197b102cf1255a
//
// JSON grammar:
// https://github.com/mna/pigeon/blob/master/examples/json/json.peg
//
// Excel:
// https://mrcsparker.wordpress.com/2015/07/26/excel-formula-grammar-for-peg-js/
//
// https://pkg.go.dev/github.com/mna/pigeon:
//

package ast

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 22, col: 1, offset: 538},
			expr: &actionExpr{
				pos: position{line: 22, col: 10, offset: 547},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 22, col: 10, offset: 547},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 22, col: 10, offset: 547},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 22, col: 15, offset: 552},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 22, col: 20, offset: 557},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 26, col: 1, offset: 591},
			expr: &actionExpr{
				pos: position{line: 26, col: 9, offset: 599},
				run: (*parser).callonExpr1,
				expr: &seqExpr{
					pos: position{line: 26, col: 9, offset: 599},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 26, col: 9, offset: 599},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 26, col: 11, offset: 601},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 26, col: 17, offset: 607},
								name: "Term",
							},
						},
						&labeledExpr{
							pos:   position{line: 26, col: 22, offset: 612},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 26, col: 27, offset: 617},
								expr: &seqExpr{
									pos: position{line: 26, col: 29, offset: 619},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 26, col: 29, offset: 619},
											name: "_",
										},
										&choiceExpr{
											pos: position{line: 26, col: 33, offset: 623},
											alternatives: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 26, col: 33, offset: 623},
													name: "AddOp",
												},
												&ruleRefExpr{
													pos:  position{line: 26, col: 41, offset: 631},
													name: "CompOp",
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 26, col: 50, offset: 640},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 26, col: 52, offset: 642},
											name: "Term",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 26, col: 60, offset: 650},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Term",
			pos:  position{line: 30, col: 1, offset: 701},
			expr: &actionExpr{
				pos: position{line: 30, col: 9, offset: 709},
				run: (*parser).callonTerm1,
				expr: &seqExpr{
					pos: position{line: 30, col: 9, offset: 709},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 30, col: 9, offset: 709},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 30, col: 15, offset: 715},
								name: "Factor",
							},
						},
						&labeledExpr{
							pos:   position{line: 30, col: 22, offset: 722},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 30, col: 27, offset: 727},
								expr: &seqExpr{
									pos: position{line: 30, col: 29, offset: 729},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 30, col: 29, offset: 729},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 30, col: 31, offset: 731},
											name: "MulOp",
										},
										&ruleRefExpr{
											pos:  position{line: 30, col: 37, offset: 737},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 30, col: 39, offset: 739},
											name: "Factor",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Function",
			pos:  position{line: 34, col: 1, offset: 798},
			expr: &actionExpr{
				pos: position{line: 34, col: 13, offset: 810},
				run: (*parser).callonFunction1,
				expr: &seqExpr{
					pos: position{line: 34, col: 13, offset: 810},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 34, col: 13, offset: 810},
							label: "fn",
							expr: &oneOrMoreExpr{
								pos: position{line: 34, col: 16, offset: 813},
								expr: &ruleRefExpr{
									pos:  position{line: 34, col: 16, offset: 813},
									name: "AlphaNum",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 26, offset: 823},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 34, col: 28, offset: 825},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 32, offset: 829},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 34, col: 34, offset: 831},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 34, col: 39, offset: 836},
								expr: &ruleRefExpr{
									pos:  position{line: 34, col: 39, offset: 836},
									name: "Args",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 34, col: 45, offset: 842},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "Args",
			pos:  position{line: 40, col: 1, offset: 1019},
			expr: &actionExpr{
				pos: position{line: 40, col: 9, offset: 1027},
				run: (*parser).callonArgs1,
				expr: &seqExpr{
					pos: position{line: 40, col: 9, offset: 1027},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 40, col: 9, offset: 1027},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 15, offset: 1033},
								name: "Expr",
							},
						},
						&labeledExpr{
							pos:   position{line: 40, col: 20, offset: 1038},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 40, col: 25, offset: 1043},
								expr: &seqExpr{
									pos: position{line: 40, col: 27, offset: 1045},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 40, col: 27, offset: 1045},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 40, col: 29, offset: 1047},
											val:        ",",
											ignoreCase: false,
											want:       "\",\"",
										},
										&ruleRefExpr{
											pos:  position{line: 40, col: 33, offset: 1051},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 40, col: 35, offset: 1053},
											name: "Expr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Factor",
			pos:  position{line: 56, col: 1, offset: 1401},
			expr: &choiceExpr{
				pos: position{line: 56, col: 11, offset: 1411},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 56, col: 11, offset: 1411},
						run: (*parser).callonFactor2,
						expr: &seqExpr{
							pos: position{line: 56, col: 11, offset: 1411},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 56, col: 11, offset: 1411},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&labeledExpr{
									pos:   position{line: 56, col: 15, offset: 1415},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 56, col: 20, offset: 1420},
										name: "Expr",
									},
								},
								&litMatcher{
									pos:        position{line: 56, col: 25, offset: 1425},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 58, col: 5, offset: 1458},
						run: (*parser).callonFactor8,
						expr: &labeledExpr{
							pos:   position{line: 58, col: 5, offset: 1458},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 58, col: 11, offset: 1464},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "AddOp",
			pos:  position{line: 62, col: 1, offset: 1501},
			expr: &actionExpr{
				pos: position{line: 62, col: 10, offset: 1510},
				run: (*parser).callonAddOp1,
				expr: &choiceExpr{
					pos: position{line: 62, col: 12, offset: 1512},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 62, col: 12, offset: 1512},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
						&litMatcher{
							pos:        position{line: 62, col: 18, offset: 1518},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
					},
				},
			},
		},
		{
			name: "MulOp",
			pos:  position{line: 66, col: 1, offset: 1564},
			expr: &actionExpr{
				pos: position{line: 66, col: 10, offset: 1573},
				run: (*parser).callonMulOp1,
				expr: &choiceExpr{
					pos: position{line: 66, col: 12, offset: 1575},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 66, col: 12, offset: 1575},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
						&litMatcher{
							pos:        position{line: 66, col: 18, offset: 1581},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
					},
				},
			},
		},
		{
			name: "CompOp",
			pos:  position{line: 70, col: 1, offset: 1627},
			expr: &actionExpr{
				pos: position{line: 70, col: 11, offset: 1637},
				run: (*parser).callonCompOp1,
				expr: &choiceExpr{
					pos: position{line: 70, col: 12, offset: 1638},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 70, col: 12, offset: 1638},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&litMatcher{
							pos:        position{line: 70, col: 18, offset: 1644},
							val:        "<>",
							ignoreCase: false,
							want:       "\"<>\"",
						},
						&litMatcher{
							pos:        position{line: 70, col: 25, offset: 1651},
							val:        "<=",
							ignoreCase: false,
							want:       "\"<=\"",
						},
						&litMatcher{
							pos:        position{line: 70, col: 32, offset: 1658},
							val:        "<",
							ignoreCase: false,
							want:       "\"<\"",
						},
						&litMatcher{
							pos:        position{line: 70, col: 38, offset: 1664},
							val:        ">=",
							ignoreCase: false,
							want:       "\">=\"",
						},
						&litMatcher{
							pos:        position{line: 70, col: 45, offset: 1671},
							val:        ">",
							ignoreCase: false,
							want:       "\">\"",
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 74, col: 1, offset: 1706},
			expr: &actionExpr{
				pos: position{line: 74, col: 10, offset: 1715},
				run: (*parser).callonValue1,
				expr: &seqExpr{
					pos: position{line: 74, col: 10, offset: 1715},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 74, col: 10, offset: 1715},
							label: "val",
							expr: &choiceExpr{
								pos: position{line: 74, col: 16, offset: 1721},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 74, col: 16, offset: 1721},
										name: "Object",
									},
									&ruleRefExpr{
										pos:  position{line: 74, col: 25, offset: 1730},
										name: "Array",
									},
									&ruleRefExpr{
										pos:  position{line: 74, col: 33, offset: 1738},
										name: "Number",
									},
									&ruleRefExpr{
										pos:  position{line: 74, col: 42, offset: 1747},
										name: "String",
									},
									&ruleRefExpr{
										pos:  position{line: 74, col: 51, offset: 1756},
										name: "Bool",
									},
									&ruleRefExpr{
										pos:  position{line: 74, col: 58, offset: 1763},
										name: "Null",
									},
									&ruleRefExpr{
										pos:  position{line: 74, col: 65, offset: 1770},
										name: "Function",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 76, offset: 1781},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 78, col: 1, offset: 1812},
			expr: &actionExpr{
				pos: position{line: 78, col: 11, offset: 1822},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 78, col: 11, offset: 1822},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 78, col: 11, offset: 1822},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 78, col: 15, offset: 1826},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 78, col: 17, offset: 1828},
							label: "vals",
							expr: &zeroOrOneExpr{
								pos: position{line: 78, col: 22, offset: 1833},
								expr: &seqExpr{
									pos: position{line: 78, col: 24, offset: 1835},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 78, col: 24, offset: 1835},
											name: "String",
										},
										&ruleRefExpr{
											pos:  position{line: 78, col: 31, offset: 1842},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 78, col: 33, offset: 1844},
											val:        ":",
											ignoreCase: false,
											want:       "\":\"",
										},
										&ruleRefExpr{
											pos:  position{line: 78, col: 37, offset: 1848},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 78, col: 39, offset: 1850},
											name: "Expr",
										},
										&zeroOrMoreExpr{
											pos: position{line: 78, col: 44, offset: 1855},
											expr: &seqExpr{
												pos: position{line: 78, col: 46, offset: 1857},
												exprs: []interface{}{
													&litMatcher{
														pos:        position{line: 78, col: 46, offset: 1857},
														val:        ",",
														ignoreCase: false,
														want:       "\",\"",
													},
													&ruleRefExpr{
														pos:  position{line: 78, col: 50, offset: 1861},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 78, col: 52, offset: 1863},
														name: "String",
													},
													&ruleRefExpr{
														pos:  position{line: 78, col: 59, offset: 1870},
														name: "_",
													},
													&litMatcher{
														pos:        position{line: 78, col: 61, offset: 1872},
														val:        ":",
														ignoreCase: false,
														want:       "\":\"",
													},
													&ruleRefExpr{
														pos:  position{line: 78, col: 65, offset: 1876},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 78, col: 67, offset: 1878},
														name: "Expr",
													},
												},
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 78, col: 78, offset: 1889},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "Array",
			pos:  position{line: 97, col: 1, offset: 2572},
			expr: &actionExpr{
				pos: position{line: 97, col: 10, offset: 2581},
				run: (*parser).callonArray1,
				expr: &seqExpr{
					pos: position{line: 97, col: 10, offset: 2581},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 97, col: 10, offset: 2581},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 14, offset: 2585},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 97, col: 16, offset: 2587},
							label: "vals",
							expr: &zeroOrOneExpr{
								pos: position{line: 97, col: 21, offset: 2592},
								expr: &seqExpr{
									pos: position{line: 97, col: 23, offset: 2594},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 97, col: 23, offset: 2594},
											name: "Expr",
										},
										&zeroOrMoreExpr{
											pos: position{line: 97, col: 28, offset: 2599},
											expr: &seqExpr{
												pos: position{line: 97, col: 30, offset: 2601},
												exprs: []interface{}{
													&litMatcher{
														pos:        position{line: 97, col: 30, offset: 2601},
														val:        ",",
														ignoreCase: false,
														want:       "\",\"",
													},
													&ruleRefExpr{
														pos:  position{line: 97, col: 34, offset: 2605},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 97, col: 36, offset: 2607},
														name: "Expr",
													},
												},
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 97, col: 47, offset: 2618},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 113, col: 1, offset: 3072},
			expr: &actionExpr{
				pos: position{line: 113, col: 11, offset: 3082},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 113, col: 11, offset: 3082},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 113, col: 11, offset: 3082},
							name: "Integer",
						},
						&zeroOrOneExpr{
							pos: position{line: 113, col: 19, offset: 3090},
							expr: &seqExpr{
								pos: position{line: 113, col: 21, offset: 3092},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 113, col: 21, offset: 3092},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 113, col: 25, offset: 3096},
										expr: &ruleRefExpr{
											pos:  position{line: 113, col: 25, offset: 3096},
											name: "DecimalDigit",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 113, col: 42, offset: 3113},
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 42, offset: 3113},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 120, col: 1, offset: 3358},
			expr: &actionExpr{
				pos: position{line: 120, col: 12, offset: 3369},
				run: (*parser).callonInteger1,
				expr: &seqExpr{
					pos: position{line: 120, col: 12, offset: 3369},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 120, col: 12, offset: 3369},
							expr: &charClassMatcher{
								pos:        position{line: 120, col: 12, offset: 3369},
								val:        "[+-]",
								chars:      []rune{'+', '-'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 120, col: 18, offset: 3375},
							expr: &ruleRefExpr{
								pos:  position{line: 120, col: 18, offset: 3375},
								name: "DecimalDigit",
							},
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 124, col: 1, offset: 3438},
			expr: &seqExpr{
				pos: position{line: 124, col: 13, offset: 3450},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 124, col: 13, offset: 3450},
						val:        "e",
						ignoreCase: true,
						want:       "\"e\"i",
					},
					&zeroOrOneExpr{
						pos: position{line: 124, col: 18, offset: 3455},
						expr: &charClassMatcher{
							pos:        position{line: 124, col: 18, offset: 3455},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 124, col: 24, offset: 3461},
						expr: &ruleRefExpr{
							pos:  position{line: 124, col: 24, offset: 3461},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 126, col: 1, offset: 3478},
			expr: &charClassMatcher{
				pos:        position{line: 126, col: 17, offset: 3494},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "AlphaNum",
			pos:  position{line: 128, col: 1, offset: 3503},
			expr: &charClassMatcher{
				pos:        position{line: 128, col: 13, offset: 3515},
				val:        "[A-Za-z0-9]",
				ranges:     []rune{'A', 'Z', 'a', 'z', '0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "String",
			pos:  position{line: 132, col: 1, offset: 3578},
			expr: &choiceExpr{
				pos: position{line: 132, col: 11, offset: 3588},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 132, col: 11, offset: 3588},
						name: "DoubleQuoteString",
					},
					&ruleRefExpr{
						pos:  position{line: 132, col: 31, offset: 3608},
						name: "SingleQuoteString",
					},
				},
			},
		},
		{
			name: "DoubleQuoteString",
			pos:  position{line: 134, col: 1, offset: 3629},
			expr: &actionExpr{
				pos: position{line: 134, col: 22, offset: 3650},
				run: (*parser).callonDoubleQuoteString1,
				expr: &seqExpr{
					pos: position{line: 134, col: 22, offset: 3650},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 134, col: 22, offset: 3650},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 134, col: 26, offset: 3654},
							expr: &choiceExpr{
								pos: position{line: 134, col: 28, offset: 3656},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 134, col: 28, offset: 3656},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 134, col: 28, offset: 3656},
												expr: &ruleRefExpr{
													pos:  position{line: 134, col: 29, offset: 3657},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 134, col: 41, offset: 3669,
											},
										},
									},
									&seqExpr{
										pos: position{line: 134, col: 45, offset: 3673},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 134, col: 45, offset: 3673},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 134, col: 50, offset: 3678},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 134, col: 68, offset: 3696},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "SingleQuoteString",
			pos:  position{line: 140, col: 1, offset: 3887},
			expr: &actionExpr{
				pos: position{line: 140, col: 22, offset: 3908},
				run: (*parser).callonSingleQuoteString1,
				expr: &seqExpr{
					pos: position{line: 140, col: 22, offset: 3908},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 140, col: 22, offset: 3908},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
						&labeledExpr{
							pos:   position{line: 140, col: 26, offset: 3912},
							label: "str",
							expr: &ruleRefExpr{
								pos:  position{line: 140, col: 30, offset: 3916},
								name: "PlainString",
							},
						},
						&litMatcher{
							pos:        position{line: 140, col: 42, offset: 3928},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
					},
				},
			},
		},
		{
			name: "PlainString",
			pos:  position{line: 144, col: 1, offset: 4008},
			expr: &actionExpr{
				pos: position{line: 144, col: 16, offset: 4023},
				run: (*parser).callonPlainString1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 144, col: 16, offset: 4023},
					expr: &choiceExpr{
						pos: position{line: 144, col: 18, offset: 4025},
						alternatives: []interface{}{
							&seqExpr{
								pos: position{line: 144, col: 18, offset: 4025},
								exprs: []interface{}{
									&notExpr{
										pos: position{line: 144, col: 18, offset: 4025},
										expr: &ruleRefExpr{
											pos:  position{line: 144, col: 19, offset: 4026},
											name: "EscapedChar",
										},
									},
									&anyMatcher{
										line: 144, col: 31, offset: 4038,
									},
								},
							},
							&seqExpr{
								pos: position{line: 144, col: 35, offset: 4042},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 144, col: 35, offset: 4042},
										val:        "\\",
										ignoreCase: false,
										want:       "\"\\\\\"",
									},
									&ruleRefExpr{
										pos:  position{line: 144, col: 40, offset: 4047},
										name: "EscapeSequence",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 149, col: 1, offset: 4172},
			expr: &charClassMatcher{
				pos:        position{line: 149, col: 16, offset: 4187},
				val:        "[\\x00-\\x1f\"'\\\\]",
				chars:      []rune{'"', '\'', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 151, col: 1, offset: 4206},
			expr: &choiceExpr{
				pos: position{line: 151, col: 19, offset: 4224},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 151, col: 19, offset: 4224},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 151, col: 38, offset: 4243},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 153, col: 1, offset: 4260},
			expr: &charClassMatcher{
				pos:        position{line: 153, col: 21, offset: 4280},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 155, col: 1, offset: 4295},
			expr: &seqExpr{
				pos: position{line: 155, col: 18, offset: 4312},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 155, col: 18, offset: 4312},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 155, col: 22, offset: 4316},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 155, col: 31, offset: 4325},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 155, col: 40, offset: 4334},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 155, col: 49, offset: 4343},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 157, col: 1, offset: 4355},
			expr: &charClassMatcher{
				pos:        position{line: 157, col: 13, offset: 4367},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "Bool",
			pos:  position{line: 159, col: 1, offset: 4380},
			expr: &choiceExpr{
				pos: position{line: 159, col: 9, offset: 4388},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 159, col: 9, offset: 4388},
						run: (*parser).callonBool2,
						expr: &litMatcher{
							pos:        position{line: 159, col: 9, offset: 4388},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 161, col: 5, offset: 4463},
						run: (*parser).callonBool4,
						expr: &litMatcher{
							pos:        position{line: 161, col: 5, offset: 4463},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 165, col: 1, offset: 4541},
			expr: &actionExpr{
				pos: position{line: 165, col: 9, offset: 4549},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 165, col: 9, offset: 4549},
					val:        "null",
					ignoreCase: false,
					want:       "\"null\"",
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 169, col: 1, offset: 4616},
			expr: &zeroOrMoreExpr{
				pos: position{line: 169, col: 19, offset: 4634},
				expr: &charClassMatcher{
					pos:        position{line: 169, col: 19, offset: 4634},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 171, col: 1, offset: 4648},
			expr: &notExpr{
				pos: position{line: 171, col: 8, offset: 4655},
				expr: &anyMatcher{
					line: 171, col: 9, offset: 4656,
				},
			},
		},
	},
}

func (c *current) onInput1(expr interface{}) (interface{}, error) {

	return expr, nil
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["expr"])
}

func (c *current) onExpr1(first, rest interface{}) (interface{}, error) {

	return eval(0, 0, first, rest), nil
}

func (p *parser) callonExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr1(stack["first"], stack["rest"])
}

func (c *current) onTerm1(first, rest interface{}) (interface{}, error) {

	return eval(0, 0, first, rest), nil
}

func (p *parser) callonTerm1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTerm1(stack["first"], stack["rest"])
}

func (c *current) onFunction1(fn, args interface{}) (interface{}, error) {

	fnName := toString(fn)
	// return getFunctionNode(0, 0, fnName, args.([]interface{})...), nil
	return NewFunctionNode(0, 0, fnName, args.([]Node)), nil
}

func (p *parser) callonFunction1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunction1(stack["fn"], stack["args"])
}

func (c *current) onArgs1(first, rest interface{}) (interface{}, error) {

	slice := toIfaceSlice(rest)
	if slice == nil {
		return []Node{}, nil
	}

	args := make([]interface{}, len(slice)+1)
	args[0] = eval(0, 0, first, nil)
	for i, arg := range slice {
		val := eval(0, 0, arg.([]interface{})[3], nil)
		args[i+1] = val
	}

	return toNodeSlice(args), nil
}

func (p *parser) callonArgs1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgs1(stack["first"], stack["rest"])
}

func (c *current) onFactor2(expr interface{}) (interface{}, error) {

	return expr, nil
}

func (p *parser) callonFactor2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFactor2(stack["expr"])
}

func (c *current) onFactor8(value interface{}) (interface{}, error) {

	return value, nil
}

func (p *parser) callonFactor8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFactor8(stack["value"])
}

func (c *current) onAddOp1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonAddOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddOp1()
}

func (c *current) onMulOp1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonMulOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMulOp1()
}

func (c *current) onCompOp1() (interface{}, error) {

	return c.text, nil
}

func (p *parser) callonCompOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCompOp1()
}

func (c *current) onValue1(val interface{}) (interface{}, error) {

	return val, nil
}

func (p *parser) callonValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["val"])
}

func (c *current) onObject1(vals interface{}) (interface{}, error) {

	// res := make(map[string]interface{})
	valsSl := toIfaceSlice(vals)
	res := make([]ObjectItem, 0, len(valsSl))
	if len(valsSl) == 0 {
		return NewObjectNode(c.pos.line, c.pos.col, res), nil
	}
	// res[valsSl[0].(string)] = valsSl[4]
	res = append(res, ObjectItem{Key: valsSl[0].(StringNode).Value, Value: valsSl[4].(Node)})

	restSl := toIfaceSlice(valsSl[5])
	for _, v := range restSl {
		vSl := toIfaceSlice(v)
		// res[vSl[2].(string)] = vSl[6]
		res = append(res, ObjectItem{Key: vSl[2].(StringNode).Value, Value: vSl[6].(Node)})
	}
	return NewObjectNode(c.pos.line, c.pos.col, res), nil
}

func (p *parser) callonObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["vals"])
}

func (c *current) onArray1(vals interface{}) (interface{}, error) {

	valsSl := toIfaceSlice(vals)
	if len(valsSl) == 0 {
		return NewArrayNode(c.pos.line, c.pos.col, []Node{}), nil
	}
	res := []interface{}{valsSl[0]}
	restSl := toIfaceSlice(valsSl[1])
	for _, v := range restSl {
		vSl := toIfaceSlice(v)
		res = append(res, vSl[2])
	}
	return NewArrayNode(c.pos.line, c.pos.col, toNodeSlice(res)), nil
}

func (p *parser) callonArray1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray1(stack["vals"])
}

func (c *current) onNumber1() (interface{}, error) {

	// JSON numbers have the same syntax as Go, and are parseable using
	// strconv.ParseFloat
	value, err := strconv.ParseFloat(string(c.text), 64)
	return NewNumberNode(c.pos.line, c.pos.col, Number(value)), err
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onInteger1() (interface{}, error) {

	return strconv.Atoi(string(c.text))
}

func (p *parser) callonInteger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onDoubleQuoteString1() (interface{}, error) {

	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)
	value, err := strconv.Unquote(string(c.text))
	return NewStringNode(c.pos.line, c.pos.col, value), err
}

func (p *parser) callonDoubleQuoteString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoubleQuoteString1()
}

func (c *current) onSingleQuoteString1(str interface{}) (interface{}, error) {

	return NewStringNode(c.pos.line, c.pos.col, str.(string)), nil
}

func (p *parser) callonSingleQuoteString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSingleQuoteString1(stack["str"])
}

func (c *current) onPlainString1() (interface{}, error) {

	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)
	return string(c.text), nil
}

func (p *parser) callonPlainString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPlainString1()
}

func (c *current) onBool2() (interface{}, error) {

	return NewBooleanNode(c.pos.line, c.pos.col, true), nil
}

func (p *parser) callonBool2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool2()
}

func (c *current) onBool4() (interface{}, error) {

	return NewBooleanNode(c.pos.line, c.pos.col, false), nil
}

func (p *parser) callonBool4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool4()
}

func (c *current) onNull1() (interface{}, error) {

	return NewNullNode(c.pos.line, c.pos.col), nil
}

func (p *parser) callonNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
